---
- hosts: haproxy
  become: yes
  remote_user: ubuntu
  gather_facts: false
  pre_tasks:
     - raw: sudo apt-get -y install python-simplejson
     # action: setup will gather facts after python2 has been installed
     - action: setup
  # vars:
  #   master_ip: "{{ master_ip }}"
  #   slave1_ip: "{{ slave1_ip }}"
  #   slave2_ip: "{{ slave2_ip }}"
  tasks:
    - name: Install mysql-client
      apt: name={{ item }} update_cache=yes state=present
      with_items:
      - mysql-client
      - haproxy

    - name: Update haproxy.cfg
      template:
        src: ./haproxy.conf.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart haproxy
  
  handlers:
    - name: Restart haproxy
      service: name=haproxy state=restarted